//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose 
//values do not exceed four million, find the sum of the even-valued terms.

object Problem2 {

	def main(args: Array[String]){
		var a, b, sumEven = 0
		for (i <- 0 to 4000000){
			i = a + b
			b = i
			a = b
			if(b % 2 == 0){
				sumEven += sumEven + i
			}
		}
		println(sumEven)
	}
	  
}